# Generated by Django 5.2.4 on 2025-08-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_category_updated_at_alter_item_updated_at_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('stock_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier')),
            ],
        ),
    ]
