# Generated by Django 5.2.4 on 2025-08-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stockin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='cate_id',
        ),
    ]
